color: added --c-hom option
tanlongzhi/dip-c pull request #50
Opened 2022-08-18 21:02 UTC by tarak77

2022-08-20 18:15 UTC, tanlongzhi commented on color.py
> +        sys.stderr.write("  --c-hom=<color.txt>    color by a list of homolog specific locus-color pairs (tab-delimited: chr, locus, color)\n")
Please change "chr, locus, color" to "homolog, locus, color"

2022-08-20 18:16 UTC, tanlongzhi commented on color.py
> +        ref_name_ref_locus_colors = {}
Please change "ref_name_ref_locus_colors" to "hom_name_ref_locus_colors"

2022-08-20 18:16 UTC, tanlongzhi commented on color.py
> +            ref_name, ref_locus, color = color_file_line.strip().split("\t")
Please change "ref_name" to "hom_name"

2022-08-20 18:16 UTC, tanlongzhi commented on color.py
> +            ref_name_ref_locus_colors[(ref_name, ref_locus)] = color
Please change accordingly

2022-08-20 18:16 UTC, tanlongzhi commented on color.py
> +                color = ref_name_ref_locus_colors[(g3d_particle.get_hom_name(), g3d_particle.get_ref_locus())]
Please change accordingly

2022-08-20 18:17 UTC, tanlongzhi requested changes
Please see my inline comments to change variable names for clarity

2022-08-21 15:15 UTC, tarak77 commented
made changes

2022-08-21 15:51 UTC, tanlongzhi approved these changes

2022-08-21 15:52 UTC, merged